name: cpu-tests

on:
  pull_request:
  push:
    branches: master

jobs:
  test-linux:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 5
      matrix:
        python-version: [ '3.7', '3.8', '3.9', '3.11', '3.12']

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        pip install -e .

    - name: Test with unittest
      run: |
        python -m unittest -k CPU
    - name: Test cpu inference
      run: |
        python -m unittest -k knee_itk
